### ISSUE TITLE
Failed to run "python __main__.py"

### ISSUE THREAD

**Issue by chenKeasar** [OpenProtein/openprotein#26] opened 2019-05-18 15:26 UTC
Hi, 
thanks for making this package available.

Just cloned and run "python __main__.py" and got the error message:
 File "C:\Users\keasar\Work\meshiMC\openprotein_new\models.py", line 49, in _get_network_emissions
    (data, bi_lstm_batches), self.hidden_layer = self.bi_lstm(packed_input_sequences, self.hidden_layer)

ValueError: too many values to unpack (expected 2)

The full output is below.

Thanks,
Chen

Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.5.0 -- An enhanced Interactive Python.

runfile('C:/Users/keasar/Work/meshiMC/openprotein_new/__main__.py', wdir='C:/Users/keasar/Work/meshiMC/openprotein_new')
C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\site-packages\Bio\PDB\Vector.py:42: BiopythonDeprecationWarning: The module Bio.PDB.Vector has been deprecated in favor of new module Bio.PDB.vectors to solve a name collision with the class Vector. For the class Vector, and vector functions like calc_angle, import from Bio.PDB instead.
  "import from Bio.PDB instead.", BiopythonDeprecationWarning)
------------------------
--- OpenProtein v0.1 ---
------------------------
Starting pre-processing of raw data...
['data/raw\\sample.txt']
Processing raw data file sample.txt
 * Serving Flask app "dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Wrote output to 1 proteins to data/preprocessed/sample.txt.hdf5
Completed pre-processing.
2019-05-18 17:59:06: Embed time: 0.0
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\keasar\Work\meshiMC\openprotein_new\dashboard.py", line 45, in run
    call(["/bin/bash", "start_web_app.sh"])
  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 143, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)
  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Traceback (most recent call last):

  File "<ipython-input-1-d98c69b2ecab>", line 1, in <module>
    runfile('C:/Users/keasar/Work/meshiMC/openprotein_new/__main__.py', wdir='C:/Users/keasar/Work/meshiMC/openprotein_new')

  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\keasar\Work\python\Anaconda\envs\pytorchenv\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/keasar/Work/meshiMC/openprotein_new/__main__.py", line 67, in <module>
    minimum_updates=args.minimum_updates)

  File "C:\Users\keasar\Work\meshiMC\openprotein_new\training.py", line 38, in train_model
    loss = model.compute_loss(training_minibatch)

  File "C:\Users\keasar\Work\meshiMC\openprotein_new\openprotein.py", line 45, in compute_loss
    emissions, backbone_atoms_padded, batch_sizes = self._get_network_emissions(original_aa_string)

  File "C:\Users\keasar\Work\meshiMC\openprotein_new\models.py", line 49, in _get_network_emissions
    (data, bi_lstm_batches), self.hidden_layer = self.bi_lstm(packed_input_sequences, self.hidden_layer)

ValueError: too many values to unpack (expected 2)

**Comment by JeppeHallgren** [comment] 2019-05-18 15:37
Hi @chenKeasar , looks like there was a breaking change the a recent pytorch version for the bi_lstm API. I've fixed this in https://github.com/OpenProtein/openprotein/pull/27 . Please pull the latest master branch and let me know if the problem is fixed. Thanks!

**Comment by chenKeasar** [comment] 2019-05-18 16:16
Many thanks.
I cloned again and it is running.
Chen

**Comment by JeppeHallgren** [comment] 2019-05-18 16:17
Awesome! Closing this issue then.

**Closed by JeppeHallgren** 2019-05-18 16:17 UTC
